#!/bin/bash

# This bash script uses the current working directory to create a simple
# script to run the tmgc command anywhere in a user's
# workspace.

cmdScript=$(pwd)/.venv/bin/tmgc

cat << CMD_SCRIPT > $HOME/.local/bin/tmgcpy
#!/bin/sh

# This shell script was created by the tmGrammar tool
#       './scripts/installEditableTMGCPYCommand'
# script.

exec $cmdScript \$@
CMD_SCRIPT

chmod a+x $HOME/.local/bin/tmgcpy

echo ""
echo "Editable tmgcpy command has been created"
echo ""
